/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_peercast_core_PeerCastService */

#ifndef _Included_org_peercast_core_PeerCastService
#define _Included_org_peercast_core_PeerCastService
#ifdef __cplusplus
extern "C" {
#endif
#undef org_peercast_core_PeerCastService_MSG_SERVICE_REGISTER_CLIENT
#define org_peercast_core_PeerCastService_MSG_SERVICE_REGISTER_CLIENT 0L
#undef org_peercast_core_PeerCastService_MSG_SERVICE_UNREGISTER_CLIENT
#define org_peercast_core_PeerCastService_MSG_SERVICE_UNREGISTER_CLIENT 1L
#undef org_peercast_core_PeerCastService_MSG_SERVICE_QUERY_SERVER_PORT
#define org_peercast_core_PeerCastService_MSG_SERVICE_QUERY_SERVER_PORT 16L
#undef org_peercast_core_PeerCastService_MSG_SERVICE_ON_SERVER_START
#define org_peercast_core_PeerCastService_MSG_SERVICE_ON_SERVER_START 32L
#undef org_peercast_core_PeerCastService_MSG_SERVICE_ON_NOTIFY_MESSAGE
#define org_peercast_core_PeerCastService_MSG_SERVICE_ON_NOTIFY_MESSAGE 33L
/*
 * Class:     org_peercast_core_PeerCastService
 * Method:    nativeStart
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_peercast_core_PeerCastService_nativeStart
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_peercast_core_PeerCastService
 * Method:    nativeQuit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_peercast_core_PeerCastService_nativeQuit
  (JNIEnv *, jobject);

/*
 * Class:     org_peercast_core_PeerCastService
 * Method:    nativeClassInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_peercast_core_PeerCastService_nativeClassInit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
