/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_peercast_core_PeerCastService */

#ifndef _Included_org_peercast_core_PeerCastService
#define _Included_org_peercast_core_PeerCastService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_peercast_core_PeerCastService
 * Method:    nativeStart
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_peercast_core_PeerCastService_nativeStart
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     org_peercast_core_PeerCastService
 * Method:    nativeQuit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_peercast_core_PeerCastService_nativeQuit
  (JNIEnv *, jclass);

/*
 * Class:     org_peercast_core_PeerCastService
 * Method:    nativeClassInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_peercast_core_PeerCastService_nativeClassInit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
